INSERT INTO public.properties (
  id,
  title,
  purpose,
  property_type,
  location,
  city,
  price,
  price_period,
  bedrooms,
  bathrooms,
  parking,
  furnished,
  serviced,
  featured,
  image,
  description,
  features,
  created_at
) VALUES
  (
    'modern-2-bedroom-flat-ugbowo',
    'Modern 2 Bedroom Flat',
    'rent',
    'Flat',
    'Ugbowo',
    'Benin City',
    1500000,
    'year',
    2,
    2,
    true,
    false,
    false,
    true,
    'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=88',
    'A well-planned flat in a connected Ugbowo neighbourhood, with comfortable everyday living spaces.',
    ARRAY['Parking', 'Estate security', 'Fitted kitchen'],
    now()
  ),
  (
    'serviced-3-bedroom-apartment-gra',
    'Serviced 3 Bedroom Apartment',
    'rent',
    'Serviced Apartment',
    'GRA',
    'Benin City',
    3200000,
    'year',
    3,
    3,
    true,
    true,
    true,
    true,
    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=88',
    'A polished serviced apartment with generous rooms and the convenience of managed living in GRA.',
    ARRAY['Furnished', '24-hour power', 'Parking'],
    now()
  ),
  (
    '4-bedroom-duplex-airport-road',
    '4 Bedroom Duplex',
    'rent',
    'Duplex',
    'Airport Road',
    'Benin City',
    4500000,
    'year',
    4,
    4,
    true,
    false,
    false,
    false,
    'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=88',
    'A spacious family duplex with private compound space and easy access to Airport Road.',
    ARRAY['Gated compound', 'Parking', 'Security'],
    now()
  ),
  (
    'newly-built-mini-flat-sapele-road',
    'Newly Built Mini Flat',
    'rent',
    'Mini Flat',
    'Sapele Road',
    'Benin City',
    900000,
    'year',
    1,
    1,
    true,
    false,
    false,
    false,
    'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=88',
    'A compact newly built mini flat suited to simple, practical city living near Sapele Road.',
    ARRAY['Newly built', 'Parking', 'Water supply'],
    now()
  ),
  (
    'modern-2-bedroom-apartment-ikpoba-hill',
    'Modern 2 Bedroom Apartment',
    'rent',
    'Apartment',
    'Ikpoba Hill',
    'Benin City',
    1200000,
    'year',
    2,
    2,
    true,
    false,
    false,
    false,
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=88',
    'A calm two-bedroom apartment with a bright living area in an established Ikpoba Hill setting.',
    ARRAY['Parking', 'Fitted kitchen', 'Security'],
    now()
  ),
  (
    'luxury-3-bedroom-flat-lekki',
    'Luxury 3 Bedroom Flat',
    'rent',
    'Flat',
    'Lekki',
    'Lagos',
    4800000,
    'year',
    3,
    3,
    true,
    true,
    true,
    true,
    'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=88',
    'A polished serviced flat with generous entertaining spaces in a secure Lekki development.',
    ARRAY['Furnished', 'Estate security', 'Backup power'],
    now()
  ),
  (
    'modern-2-bedroom-apartment-ikeja',
    'Modern 2 Bedroom Apartment',
    'rent',
    'Apartment',
    'Ikeja',
    'Lagos',
    2800000,
    'year',
    2,
    2,
    true,
    false,
    false,
    false,
    'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=88',
    'A modern apartment with practical proportions and covered parking in Ikeja.',
    ARRAY['Covered parking', 'Water supply', 'Security'],
    now()
  ),
  (
    '4-bedroom-family-duplex-abuja',
    '4 Bedroom Family Duplex',
    'rent',
    'Duplex',
    'Maitama',
    'Abuja',
    6500000,
    'year',
    4,
    5,
    true,
    false,
    false,
    false,
    'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=88',
    'A large family duplex with room for entertaining and a paved compound in Maitama.',
    ARRAY['Paved compound', 'Parking', 'Security'],
    now()
  ),
  (
    '4-bedroom-duplex-gra-sale',
    '4 Bedroom Duplex',
    'sale',
    'Duplex',
    'GRA',
    'Benin City',
    45000000,
    'sale',
    4,
    4,
    true,
    false,
    false,
    true,
    'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=88',
    'A substantial GRA duplex with a secure compound and room to grow into.',
    ARRAY['Secure compound', 'Parking', 'Garden space'],
    now()
  ),
  (
    'modern-3-bedroom-apartment-lekki-sale',
    'Modern 3 Bedroom Apartment',
    'sale',
    'Apartment',
    'Lekki',
    'Lagos',
    38000000,
    'sale',
    3,
    3,
    true,
    false,
    true,
    true,
    'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=88',
    'A contemporary three-bedroom apartment in a serviced Lekki development.',
    ARRAY['Serviced estate', 'Parking', 'Backup power'],
    now()
  ),
  (
    'family-duplex-abuja-sale',
    'Family Duplex',
    'sale',
    'Estate',
    'Maitama',
    'Abuja',
    65000000,
    'sale',
    4,
    5,
    true,
    false,
    false,
    false,
    'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=88',
    'A generous Abuja family home with multiple living areas and a private compound.',
    ARRAY['Private compound', 'Parking', 'Security'],
    now()
  ),
  (
    'contemporary-apartment-port-harcourt',
    'Contemporary Apartment',
    'sale',
    'Apartment',
    'Old GRA',
    'Port Harcourt',
    28000000,
    'sale',
    3,
    3,
    true,
    false,
    false,
    false,
    'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=88',
    'A clean, contemporary apartment with comfortable proportions in Old GRA.',
    ARRAY['Fitted kitchen', 'Parking', 'Water supply'],
    now()
  ),
  (
    'modern-flat-ibadan',
    'Modern 2 Bedroom Flat',
    'sale',
    'Flat',
    'Jericho',
    'Ibadan',
    22000000,
    'sale',
    2,
    2,
    true,
    false,
    false,
    false,
    'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=88',
    'A practical two-bedroom flat with a quiet residential feel in Jericho, Ibadan.',
    ARRAY['Parking', 'Estate security', 'Water supply'],
    now()
  );
