export type Property = {
  id: string;
  title: string;
  location: string;
  price: string;
  priceValue: number;
  purpose: "rent" | "buy";
  propertyType: string;
  bedrooms: number;
  bathrooms: number;
  area: string;
  parking: string;
  image: string;
  imageAlt: string;
};

export const properties: Property[] = [
  {
    id: "modern-2-bedroom-flat-ugbowo",
    title: "Modern 2 Bedroom Flat",
    location: "Ugbowo, Benin City",
    price: "₦1,500,000 / year",
    priceValue: 1500000,
    purpose: "rent",
    propertyType: "2 Bedroom Flat",
    bedrooms: 2,
    bathrooms: 2,
    area: "120 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Bright open-plan living room in a modern Nigerian-style flat",
  },
  {
    id: "serviced-3-bedroom-apartment-gra",
    title: "Serviced 3 Bedroom Apartment",
    location: "GRA, Benin City",
    price: "₦3,200,000 / year",
    priceValue: 3200000,
    purpose: "rent",
    propertyType: "Serviced Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: "180 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Polished kitchen and living area in a serviced apartment",
  },
  {
    id: "4-bedroom-duplex-airport-road",
    title: "4 Bedroom Duplex",
    location: "Airport Road, Benin City",
    price: "₦4,500,000 / year",
    priceValue: 4500000,
    purpose: "rent",
    propertyType: "Duplex",
    bedrooms: 4,
    bathrooms: 4,
    area: "260 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Contemporary duplex with a gated compound and driveway",
  },
  {
    id: "newly-built-mini-flat-sapele-road",
    title: "Newly Built Mini Flat",
    location: "Sapele Road, Benin City",
    price: "₦900,000 / year",
    priceValue: 900000,
    purpose: "rent",
    propertyType: "Mini Flat",
    bedrooms: 1,
    bathrooms: 1,
    area: "75 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Compact, newly finished mini flat bedroom",
  },
  {
    id: "modern-2-bedroom-apartment-ikpoba-hill",
    title: "Modern 2 Bedroom Apartment",
    location: "Ikpoba Hill, Benin City",
    price: "₦1,200,000 / year",
    priceValue: 1200000,
    purpose: "rent",
    propertyType: "2 Bedroom Flat",
    bedrooms: 2,
    bathrooms: 2,
    area: "125 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Modern two-bedroom apartment living area",
  },
  {
    id: "luxury-3-bedroom-flat-lekki",
    title: "Luxury 3 Bedroom Flat",
    location: "Lekki, Lagos",
    price: "₦4,800,000 / year",
    priceValue: 4800000,
    purpose: "rent",
    propertyType: "3 Bedroom Flat",
    bedrooms: 3,
    bathrooms: 3,
    area: "210 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Spacious serviced apartment interior with warm finishes",
  },
  {
    id: "modern-2-bedroom-apartment-ikeja",
    title: "Modern 2 Bedroom Apartment",
    location: "Ikeja, Lagos",
    price: "₦2,800,000 / year",
    priceValue: 2800000,
    purpose: "rent",
    propertyType: "2 Bedroom Flat",
    bedrooms: 2,
    bathrooms: 2,
    area: "140 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Modern apartment frontage with covered parking",
  },
  {
    id: "4-bedroom-family-duplex-abuja",
    title: "4 Bedroom Family Duplex",
    location: "Maitama, Abuja",
    price: "₦6,500,000 / year",
    priceValue: 6500000,
    purpose: "rent",
    propertyType: "Duplex",
    bedrooms: 4,
    bathrooms: 5,
    area: "320 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600566753051-7f6b6b1e9f8f?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Large family duplex with a paved residential compound",
  },
  {
    id: "4-bedroom-duplex-gra-sale",
    title: "4 Bedroom Duplex",
    location: "GRA, Benin City",
    price: "₦45,000,000",
    priceValue: 45000000,
    purpose: "buy",
    propertyType: "Duplex",
    bedrooms: 4,
    bathrooms: 4,
    area: "380 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Modern Benin City duplex with secure compound frontage",
  },
  {
    id: "modern-3-bedroom-apartment-lekki-sale",
    title: "Modern 3 Bedroom Apartment",
    location: "Lekki, Lagos",
    price: "₦38,000,000",
    priceValue: 38000000,
    purpose: "buy",
    propertyType: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    area: "220 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Modern Lagos apartment living room with generous windows",
  },
  {
    id: "family-duplex-abuja-sale",
    title: "Family Duplex",
    location: "Maitama, Abuja",
    price: "₦65,000,000",
    priceValue: 65000000,
    purpose: "buy",
    propertyType: "Duplex",
    bedrooms: 4,
    bathrooms: 5,
    area: "420 m²",
    parking: "Parking",
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=88",
    imageAlt: "Abuja family duplex interior with contemporary finishes",
  },
];